import random

class MostLikelyGame:
    def __init__(self):
        self.prompts = [
            'Most likely to become a millionaire?',
            'Most likely to join a circus?',
            'Most likely to become a reality TV star?',
            'Most likely to invent something useful?',
            'Most likely to travel to space?',
            'Most likely to forget their best friend’s birthday?',
            'Most likely to become a famous actor?',
            'Most likely to get a face tattoo?',
            'Most likely to win a Nobel Prize?',
            'Most likely to run a marathon?',
            'Most likely to cry during a movie?',
            'Most likely to become president?',
            'Most likely to get arrested for something stupid?',
            'Most likely to donate their entire savings?',
            'Most likely to eat a bug?',
            'Most likely to break a world record?',
            'Most likely to fall asleep at a party?',
            'Most likely to become a stand-up comedian?',
            'Most likely to forget their wedding anniversary?',
            'Most likely to win an Olympic medal?',
            'Most likely to get stranded on a deserted island?',
            'Most likely to become a professional gamer?',
            'Most likely to marry a celebrity?',
            'Most likely to become a motivational speaker?',
            'Most likely to own a yacht?',
            'Most likely to adopt a dozen cats?',
            'Most likely to become a spy?',
            'Most likely to win a Grammy award?',
            'Most likely to forget where they parked their car?',
            'Most likely to move to another country?',
            'Most likely to spend all their money on something stupid?',
            'Most likely to accidentally set something on fire?',
            'Most likely to live to 100 years old?',
            'Most likely to go skydiving?',
            'Most likely to become a famous YouTuber?',
            'Most likely to write a best-selling book?',
            'Most likely to become a teacher?',
            'Most likely to start a charity?',
            'Most likely to get a weird piercing?',
            'Most likely to survive a zombie apocalypse?',
            'Most likely to become a vegan?',
            'Most likely to get a terrible haircut?',
            'Most likely to become a monk?',
            'Most likely to get lost in their own neighborhood?',
            'Most likely to join a rock band?',
            'Most likely to get a tattoo of their partner’s name?',
            'Most likely to win a lottery?',
            'Most likely to break their phone screen?',
            'Most likely to forget their own birthday?',
            'Most likely to start their own business?',
            'Most likely to climb Mount Everest?',
            'Most likely to become a professional athlete?',
            'Most likely to go on a blind date?',
            'Most likely to get a pet snake?',
            'Most likely to become a doctor?',
            'Most likely to accidentally send a text to the wrong person?',
            'Most likely to dance in public?',
            'Most likely to become a model?',
            'Most likely to join the army?',
            'Most likely to dye their hair a crazy color?',
            'Most likely to win a cooking competition?',
            'Most likely to accidentally get married in Vegas?',
            'Most likely to sing in the shower?',
            'Most likely to sleep through an important event?',
            'Most likely to become a fashion designer?',
            'Most likely to adopt a child?',
            'Most likely to crash their car?',
            'Most likely to forget to pick up their kids from school?',
            'Most likely to run for political office?',
            'Most likely to get a speeding ticket?',
            'Most likely to become a famous artist?',
            'Most likely to forget to pay their bills?',
            'Most likely to bake a cake from scratch?',
            'Most likely to get a ridiculous haircut?',
            'Most likely to become a scientist?',
            'Most likely to travel the world?',
            'Most likely to start a podcast?',
            'Most likely to go bungee jumping?',
            'Most likely to get lost in a foreign country?',
            'Most likely to invent a new gadget?',
            'Most likely to become a famous chef?',
            'Most likely to forget their keys?',
            'Most likely to become a professional dancer?',
            'Most likely to buy a house?',
            'Most likely to adopt a rescue animal?',
            'Most likely to start a band?',
            'Most likely to quit their job on a whim?',
            'Most likely to swim with sharks?',
            'Most likely to build a treehouse?',
            'Most likely to become a famous writer?',
            'Most likely to go on a road trip across the country?',
            'Most likely to take up a new hobby?',
            'Most likely to start a new diet?',
            'Most likely to get a dramatic makeover?',
            'Most likely to volunteer for a good cause?',
            'Most likely to start a blog?',
            'Most likely to become a fitness guru?',
            'Most likely to learn a new language?',
            'Most likely to stay up all night binge-watching TV?',
            'Most likely to become a famous musician?',
            'Most likely to open a restaurant?'
        ]

    def get_prompt(self):
        return random.choice(self.prompts)

most_likely_game = MostLikelyGame()
