import random

class RouletteGame:
    def __init__(self):
        self.prompts = [
            'Do 10 pushups.',
            'Take a shot.',
            'Dance for 1 minute without music.',
            'Let someone write on your face with a marker.',
            'Sing a song chosen by the group.',
            'Imitate a celebrity until someone can guess who you are.',
            'Run around the house three times.',
            'Do your best chicken dance outside on the lawn.',
            'Eat a spoonful of mustard.',
            'Talk in an accent for the next 3 rounds.',
            'Let someone tickle you for 30 seconds.',
            'Lick the floor.',
            'Speak in rhymes for the next three rounds.',
            'Pretend to be a waiter/waitress and take snack orders from everyone in the group.',
            'Wear socks on your hands for the next 10 minutes.',
            'Try to lick your elbow.',
            'Do your best impression of someone until another player can guess who you are.',
            'Do the worm.',
            'Let the person next to you redo your hairstyle.',
            'Balance a spoon on your nose for 10 seconds.',
            'Do a silly dance that lasts for 1 minute.',
            'Eat a raw onion slice.',
            'Wear your pants backward for the next round.',
            'Do 20 jumping jacks.',
            'Hold your breath for as long as you can.',
            'Act like your favorite movie character for the next 5 minutes.',
            'Eat a slice of lemon without making a face.',
            'Sing everything you say for the next 10 minutes.',
            'Act like a monkey until it’s your turn again.',
            'Run to the nearest tree and hug it.',
            'Do an impression of another player until someone can guess who you are.',
            'Let another player redo your makeup.',
            'Post an embarrassing photo on social media.',
            'Make up a story about the item to your right.',
            'Try to juggle 3 items chosen by the group.',
            'Eat a clove of raw garlic.',
            'Let someone give you a wedgie.',
            'Wear underwear on your head for the next three rounds.',
            'Let someone write a word on your forehead in a permanent marker.',
            'Speak in a high-pitched voice until your next turn.',
            'Pretend to be a waiter and take drink orders from everyone in the group.',
            'Let another player redo your hairstyle.',
            'Put an ice cube down your shirt.',
            'Pretend to be a dog until it’s your turn again.',
            'Do 15 squats.',
            'Wear your shoes on your hands for the next 10 minutes.',
            'Let the group choose a word and you have to sing a song with that word in it.',
            'Talk like a baby for the next 5 minutes.',
            'Act like a chicken until your next turn.',
            'Hold an ice cube in your hand until it melts.',
            'Do your best celebrity impression until someone can guess who you are.',
            'Wear a silly hat for the next 10 minutes.',
            'Let another player tickle you for 30 seconds.',
            'Talk with your tongue sticking out for the next 5 minutes.',
            'Pretend to be a news anchor and deliver a made-up news report.',
            'Do 20 sit-ups.',
            'Sing the chorus of your favorite song.',
            'Run to the nearest street corner and back.',
            'Do your best impression of a baby being born.',
            'Wear a toilet paper mustache for the next three rounds.',
            'Dance with no music for 1 minute.',
            'Let the person to your left draw on your face with a pen.',
            "Try to juggle three items of the group's choosing.",
            'Do your best chicken dance outside on the lawn.',
            'Wear socks on your hands for the next three rounds.',
            'Lick the floor.',
            'Talk in rhymes for the next 10 minutes.',
            'Let someone tickle you for 30 seconds.',
            'Balance a spoon on your nose for 10 seconds.',
            'Try to lick your elbow.',
            'Do your best impression of someone until another player can guess who you are.',
            'Do the worm.',
            'Let the person next to you redo your hairstyle.',
            'Balance a spoon on your nose for 10 seconds.',
            'Do a silly dance that lasts for 1 minute.',
            'Eat a raw onion slice.',
            'Wear your pants backward for the next round.',
            'Do 20 jumping jacks.',
            'Hold your breath for as long as you can.',
            'Act like your favorite movie character for the next 5 minutes.',
            'Eat a slice of lemon without making a face.',
            'Sing everything you say for the next 10 minutes.',
            'Act like a monkey until it’s your turn again.',
            'Run to the nearest tree and hug it.',
            'Do an impression of another player until someone can guess who you are.',
            'Let another player redo your makeup.',
            'Post an embarrassing photo on social media.',
            'Make up a story about the item to your right.',
            'Try to juggle 3 items chosen by the group.',
            'Eat a clove of raw garlic.',
            'Let someone give you a wedgie.',
            'Wear underwear on your head for the next three rounds.',
            'Let someone write a word on your forehead in a permanent marker.',
            'Speak in a high-pitched voice until your next turn.',
            'Pretend to be a waiter and take drink orders from everyone in the group.',
            'Let another player redo your hairstyle.',
            'Put an ice cube down your shirt.',
            'Pretend to be a dog until it’s your turn again.',
            'Do 15 squats.',
            'Wear your shoes on your hands for the next 10 minutes.',
            'Let the group choose a word and you have to sing a song with that word in it.',
            'Talk like a baby for the next 5 minutes.',
            'Act like a chicken until your next turn.',
            'Hold an ice cube in your hand until it melts.',
            'Do your best celebrity impression until someone can guess who you are.',
            'Wear a silly hat for the next 10 minutes.',
            'Let another player tickle you for 30 seconds.',
            'Talk with your tongue sticking out for the next 5 minutes.',
            'Pretend to be a news anchor and deliver a made-up news report.',
            'Do 20 sit-ups.',
            'Sing the chorus of your favorite song.',
            'Run to the nearest street corner and back.',
            'Do your best impression of a baby being born.',
            'Wear a toilet paper mustache for the next three rounds.',
            'Dance with no music for 1 minute.',
            'Let the person to your left draw on your face with a pen.',
            "Try to juggle three items of the group's choosing.",
            'Do your best chicken dance outside on the lawn.',
            'Wear socks on your hands for the next three rounds.',
            'Lick the floor.',
            'Talk in rhymes for the next 10 minutes.',
            'Let someone tickle you for 30 seconds.',
            'Balance a spoon on your nose for 10 seconds.',
            'Try to lick your elbow.',
            'Do your best impression of someone until another player can guess who you are.',
            'Do the worm.',
            'Let the person next to you redo your hairstyle.',
            'Balance a spoon on your nose for 10 seconds.',
            'Do a silly dance that lasts for 1 minute.',
            'Eat a raw onion slice.',
            'Wear your pants backward for the next round.',
            'Do 20 jumping jacks.',
            'Hold your breath for as long as you can.',
            'Act like your favorite movie character for the next 5 minutes.',
            'Eat a slice of lemon without making a face.',
            'Sing everything you say for the next 10 minutes.',
            'Act like a monkey until it’s your turn again.',
            'Run to the nearest tree and hug it.',
            'Do an impression of another player until someone can guess who you are.',
            'Let another player redo your makeup.',
            'Post an embarrassing photo on social media.',
            'Make up a story about the item to your right.',
            'Try to juggle 3 items chosen by the group.',
            'Eat a clove of raw garlic.',
            'Let someone give you a wedgie.',
            'Wear underwear on your head for the next three rounds.',
            'Let someone write a word on your forehead in a permanent marker.',
            'Speak in a high-pitched voice until your next turn.',
            'Pretend to be a waiter and take drink orders from everyone in the group.',
            'Let another player redo your hairstyle.',
            'Put an ice cube down your shirt.',
            'Pretend to be a dog until it’s your turn again.',
            'Do 15 squats.',
            'Wear your shoes on your hands for the next 10 minutes.',
            'Let the group choose a word and you have to sing a song with that word in it.',
            'Talk like a baby for the next 5 minutes.',
            'Act like a chicken until your next turn.',
            'Hold an ice cube in your hand until it melts.',
            'Do your best celebrity impression until someone can guess who you are.',
            'Wear a silly hat for the next 10 minutes.',
            'Let another player tickle you for 30 seconds.',
            'Talk with your tongue sticking out for the next 5 minutes.',
            'Pretend to be a news anchor and deliver a made-up news report.',
            'Do 20 sit-ups.',
            'Sing the chorus of your favorite song.',
            'Run to the nearest street corner and back.',
            'Do your best impression of a baby being born.',
            'Wear a toilet paper mustache for the next three rounds.',
            'Dance with no music for 1 minute.',
            'Let the person to your left draw on your face with a pen.',
            "Try to juggle three items of the group's choosing."
        ]

    def draw_card(self):
        return random.choice(self.prompts)

roulette_game = RouletteGame()
