import random

class DrunkTriviaGame:
    def __init__(self):
        self.questions = [
            ('What is the capital of France?', 'Paris'),
            ('What is the largest planet in our solar system?', 'Jupiter'),
            ('Who wrote "Romeo and Juliet"?', 'William Shakespeare'),
            ('What is the boiling point of water?', '100 degrees Celsius'),
            ('Who painted the Mona Lisa?', 'Leonardo da Vinci'),
            ('What is the smallest country in the world?', 'Vatican City'),
            ('Who is known as the "Father of Computers"?', 'Charles Babbage'),
            ('What is the chemical symbol for gold?', 'Au'),
            ('What is the longest river in the world?', 'Nile'),
            ('Which planet is known as the Red Planet?', 'Mars'),
            ('Who discovered penicillin?', 'Alexander Fleming'),
            ('What is the hardest natural substance on Earth?', 'Diamond'),
            ('What is the capital of Japan?', 'Tokyo'),
            ('Who wrote "1984"?', 'George Orwell'),
            ('What is the currency of the United Kingdom?', 'Pound Sterling'),
            ('What is the tallest mountain in the world?', 'Mount Everest'),
            ('Who painted the ceiling of the Sistine Chapel?', 'Michelangelo'),
            ('What is the capital of Canada?', 'Ottawa'),
            ('What is the chemical formula for water?', 'H2O'),
            ('Who is the author of the Harry Potter series?', 'J.K. Rowling'),
            ('What is the main ingredient in guacamole?', 'Avocado'),
            ('What is the largest ocean on Earth?', 'Pacific Ocean'),
            ('Who was the first man to walk on the moon?', 'Neil Armstrong'),
            ('What is the capital of Australia?', 'Canberra'),
            ('What is the name of the longest river in the United States?', 'Missouri River'),
            ('Who is the lead singer of the band U2?', 'Bono'),
            ('What is the hardest rock?', 'Diamond'),
            ('What is the capital of Italy?', 'Rome'),
            ('Who wrote "To Kill a Mockingbird"?', 'Harper Lee'),
            ('What is the largest organ in the human body?', 'Skin'),
            ('What is the capital of Germany?', 'Berlin'),
            ('Who was the first President of the United States?', 'George Washington'),
            ('What is the chemical symbol for sodium?', 'Na'),
            ('What is the capital of Spain?', 'Madrid'),
            ('Who painted "Starry Night"?', 'Vincent van Gogh'),
            ('What is the currency of Japan?', 'Yen'),
            ('What is the tallest building in the world?', 'Burj Khalifa'),
            ('Who discovered electricity?', 'Benjamin Franklin'),
            ('What is the capital of Russia?', 'Moscow'),
            ('What is the chemical formula for carbon dioxide?', 'CO2'),
            ('Who wrote "Pride and Prejudice"?', 'Jane Austen'),
            ('What is the main ingredient in a Bloody Mary?', 'Tomato juice'),
            ('What is the smallest planet in our solar system?', 'Mercury'),
            ('Who was the first woman to win a Nobel Prize?', 'Marie Curie'),
            ('What is the capital of Brazil?', 'Brasília'),
            ('Who painted "The Persistence of Memory"?', 'Salvador Dalí'),
            ('What is the largest desert in the world?', 'Sahara'),
            ('Who is the author of "The Great Gatsby"?', 'F. Scott Fitzgerald'),
            ('What is the chemical symbol for iron?', 'Fe'),
            ('What is the capital of South Korea?', 'Seoul'),
            ('Who discovered the law of gravity?', 'Isaac Newton'),
            ('What is the capital of Argentina?', 'Buenos Aires'),
            ('Who wrote "Moby-Dick"?', 'Herman Melville'),
            ('What is the largest mammal in the world?', 'Blue whale'),
            ('What is the capital of Mexico?', 'Mexico City'),
            ('Who painted "The Last Supper"?', 'Leonardo da Vinci'),
            ('What is the main ingredient in hummus?', 'Chickpeas'),
            ('What is the chemical symbol for potassium?', 'K'),
            ('Who is known as the "King of Pop"?', 'Michael Jackson'),
            ('What is the capital of Egypt?', 'Cairo'),
            ('Who wrote "The Catcher in the Rye"?', 'J.D. Salinger'),
            ('What is the fastest land animal?', 'Cheetah'),
            ('What is the capital of India?', 'New Delhi'),
            ('Who painted "Guernica"?', 'Pablo Picasso'),
            ('What is the chemical symbol for oxygen?', 'O'),
            ('What is the capital of China?', 'Beijing'),
            ('Who wrote "War and Peace"?', 'Leo Tolstoy'),
            ('What is the largest island in the world?', 'Greenland'),
            ('What is the capital of Greece?', 'Athens'),
            ('Who painted "The Scream"?', 'Edvard Munch'),
            ('What is the main ingredient in sushi?', 'Rice'),
            ('What is the chemical symbol for silver?', 'Ag'),
            ('What is the capital of Turkey?', 'Ankara'),
            ('Who wrote "The Odyssey"?', 'Homer'),
            ('What is the longest bone in the human body?', 'Femur'),
            ('What is the capital of Sweden?', 'Stockholm'),
            ('Who painted "The Birth of Venus"?', 'Sandro Botticelli'),
            ('What is the currency of China?', 'Yuan'),
            ('What is the largest continent on Earth?', 'Asia'),
            ('What is the capital of Norway?', 'Oslo'),
            ('Who wrote "The Divine Comedy"?', 'Dante Alighieri'),
            ('What is the tallest waterfall in the world?', 'Angel Falls'),
            ('What is the capital of Kenya?', 'Nairobi'),
            ('Who painted "The Night Watch"?', 'Rembrandt'),
            ('What is the main ingredient in moussaka?', 'Eggplant'),
            ('What is the chemical symbol for helium?', 'He'),
            ('What is the capital of Thailand?', 'Bangkok'),
            ('Who wrote "Don Quixote"?', 'Miguel de Cervantes'),
            ('What is the largest reptile in the world?', 'Saltwater crocodile'),
            ('What is the capital of the Netherlands?', 'Amsterdam'),
            ('Who painted "American Gothic"?', 'Grant Wood'),
            ('What is the currency of India?', 'Rupee'),
            ('What is the largest country in the world?', 'Russia'),
            ('What is the capital of Portugal?', 'Lisbon'),
            ('Who wrote "The Hobbit"?', 'J.R.R. Tolkien'),
            ('What is the main ingredient in paella?', 'Rice'),
            ('What is the chemical symbol for lead?', 'Pb'),
            ('What is the capital of Finland?', 'Helsinki'),
            ('Who wrote "A Brief History of Time"?', 'Stephen Hawking'),
            ('What is the tallest animal in the world?', 'Giraffe')
        ]

    def get_question(self):
        return random.choice(self.questions)

drunk_trivia_game = DrunkTriviaGame()
