import random

class WouldYouRatherGame:
    def __init__(self):
        self.prompts = [
            'Would you rather have sex with someone who never showers or someone who never brushes their teeth?',
            'Would you rather watch your parents have sex every day for the rest of your life or join in once to stop it?',
            'Would you rather accidentally send a sext to your mom or your boss?',
            'Would you rather walk in on your parents having sex or have them walk in on you?',
            'Would you rather have sex with a goat and no one knows or not have sex with a goat but everyone thinks you did?',
            'Would you rather lick someone’s armpit or have someone else lick your armpit?',
            'Would you rather have a threesome with two strangers or have sex with anyone of your choice?',
            'Would you rather always have sex in the dark or always have sex in public places?',
            'Would you rather sleep with your best friend’s partner or your partner’s best friend?',
            'Would you rather fart loudly every time you orgasm or never orgasm again?',
            'Would you rather have a small penis that can ejaculate forever or a big penis that lasts for 30 seconds?',
            'Would you rather get a blowjob or give a blowjob?',
            'Would you rather watch your partner have sex with someone else or have sex with someone else while your partner watches?',
            'Would you rather have sex with someone who has a great body or someone who is really skilled in bed?',
            'Would you rather have a one-night stand with a stranger or have sex with your best friend?',
            'Would you rather get caught masturbating by your parents or by your boss?',
            'Would you rather have sex with someone who calls you “mommy” or “daddy” or calls you by your own mother’s or father’s name?',
            'Would you rather always make out for six hours or always have sex for less than seven minutes?',
            'Would you rather have sex in a smelly bathroom or in a car on a busy street?',
            'Would you rather have a partner who is super loud in bed or super quiet?',
            'Would you rather have sex with your partner’s sibling or your best friend’s sibling?',
            'Would you rather only be able to have sex in five-minute increments for the rest of your life or only be able to have sex for five hours at a time for the rest of your life?',
            'Would you rather have sex with someone who refuses to make eye contact or someone who never speaks?',
            'Would you rather have sex with your clothes on or never be able to take them off during sex?',
            'Would you rather sleep with someone twice your age or a minor?',
            'Would you rather always cum prematurely or never cum at all?',
            'Would you rather have sex on a beach full of sand or in a public restroom full of strangers?',
            'Would you rather have your sex tape leaked or your nudes leaked?',
            'Would you rather have sex with a condom that is too tight or no condom at all?',
            'Would you rather never have sex again or never eat your favorite food again?',
            'Would you rather have sex with a stranger in public or with your best friend in private?',
            'Would you rather always have sex in missionary position or never have sex at all?',
            'Would you rather watch porn every night for the rest of your life or never watch porn again?',
            'Would you rather have sex with someone with bad breath or bad body odor?',
            'Would you rather get a tattoo of your ex’s name on your ass or on your forehead?',
            'Would you rather have sex with someone who is too rough or too gentle?',
            'Would you rather have sex with someone who never showers or never brushes their teeth?',
            'Would you rather have your nipples licked or your toes sucked?',
            'Would you rather give up sex or give up alcohol?',
            'Would you rather have sex in the same position for the rest of your life or never have sex again?',
            'Would you rather have a partner who is into BDSM or into role-playing?',
            'Would you rather have sex with a celebrity or with the person of your dreams?',
            'Would you rather sleep with someone with a huge sex drive or with someone who only wants sex once a year?',
            'Would you rather have sex in the morning or at night?',
            'Would you rather have sex with the lights on or off?',
            'Would you rather have sex with your best friend’s ex or your ex’s best friend?',
            'Would you rather have sex with someone who is too hairy or completely hairless?',
            'Would you rather sleep with your boss to get a promotion or with a celebrity for fame?',
            'Would you rather give up sex or give up kissing?',
            'Would you rather always have bad sex or never have sex again?',
            'Would you rather have sex with someone with bad breath or someone who farts during sex?',
            'Would you rather have sex with someone who is always on their phone or someone who talks too much?',
            'Would you rather have sex with someone who never showers or someone who never brushes their teeth?',
            'Would you rather have sex with a stranger in a public restroom or with your ex in your bed?',
            'Would you rather always have to whisper during sex or always have to shout?',
            'Would you rather have sex with someone who has bad breath or bad body odor?',
            'Would you rather have sex with someone who is always late or someone who is always early?',
            'Would you rather have sex with someone who talks dirty or someone who is silent?',
            'Would you rather have sex in a hot tub or on the beach?',
            'Would you rather have sex with someone who is inexperienced or someone who is overly experienced?',
            'Would you rather have sex in a public place or never have sex again?',
            'Would you rather have sex with someone who moans loudly or someone who is silent?',
            'Would you rather have sex with someone who is too aggressive or someone who is too passive?',
            'Would you rather have sex with someone who is always on their phone or someone who talks too much?',
            'Would you rather have sex with someone who never showers or someone who never brushes their teeth?',
            'Would you rather have sex with someone who is always late or someone who is always early?',
            'Would you rather have sex with someone who is inexperienced or someone who is overly experienced?',
            'Would you rather have sex with someone who moans loudly or someone who is silent?',
            'Would you rather have sex with someone who is too aggressive or someone who is too passive?',
            'Would you rather have sex with someone who is always on their phone or someone who talks too much?',
            'Would you rather have sex with someone who never showers or someone who never brushes their teeth?',
            'Would you rather have sex with someone who is always late or someone who is always early?',
            'Would you rather have sex with someone who is inexperienced or someone who is overly experienced?',
            'Would you rather have sex with someone who moans loudly or someone who is silent?',
            'Would you rather have sex with someone who is too aggressive or someone who is too passive?',
            'Would you rather have sex with someone who is always on their phone or someone who talks too much?',
            'Would you rather have sex with someone who never showers or someone who never brushes their teeth?',
            'Would you rather have sex with someone who is always late or someone who is always early?',
            'Would you rather have sex with someone who is inexperienced or someone who is overly experienced?',
            'Would you rather have sex with someone who moans loudly or someone who is silent?',
            'Would you rather have sex with someone who is too aggressive or someone who is too passive?',
            'Would you rather have sex with someone who is always on their phone or someone who talks too much?',
            'Would you rather have sex with someone who never showers or someone who never brushes their teeth?',
            'Would you rather have sex with someone who is always late or someone who is always early?',
            'Would you rather have sex with someone who is inexperienced or someone who is overly experienced?',
            'Would you rather have sex with someone who moans loudly or someone who is silent?',
            'Would you rather have sex with someone who is too aggressive or someone who is too passive?',
            'Would you rather have sex with someone who is always on their phone or someone who talks too much?',
            'Would you rather have sex with someone who never showers or someone who never brushes their teeth?',
            'Would you rather have sex with someone who is always late or someone who is always early?',
            'Would you rather have sex with someone who is inexperienced or someone who is overly experienced?',
            'Would you rather have sex with someone who moans loudly or someone who is silent?',
            'Would you rather have sex with someone who is too aggressive or someone who is too passive?',
            'Would you rather have sex with someone who is always on their phone or someone who talks too much?',
            'Would you rather have sex with someone who never showers or someone who never brushes their teeth?',
            'Would you rather have sex with someone who is always late or someone who is always early?',
            'Would you rather have sex with someone who is inexperienced or someone who is overly experienced?',
            'Would you rather have sex with someone who moans loudly or someone who is silent?',
            'Would you rather have sex with someone who is too aggressive or someone who is too passive?',
            'Would you rather have sex with someone who is always on their phone or someone who talks too much?',
            'Would you rather have sex with someone who never showers or someone who never brushes their teeth?',
            'Would you rather have sex with someone who is always late or someone who is always early?',
            'Would you rather have sex with someone who is inexperienced or someone who is overly experienced?',
            'Would you rather have sex with someone who moans loudly or someone who is silent?',
            'Would you rather have sex with someone who is too aggressive or someone who is too passive?',
            'Would you rather have sex with someone who is always on their phone or someone who talks too much?',
            'Would you rather have sex with someone who never showers or someone who never brushes their teeth?',
            'Would you rather have sex with someone who is always late or someone who is always early?',
            'Would you rather have sex with someone who is inexperienced or someone who is overly experienced?',
            'Would you rather have sex with someone who moans loudly or someone who is silent?',
            'Would you rather have sex with someone who is too aggressive or someone who is too passive?',
            'Would you rather have sex with someone who is always on their phone or someone who talks too much?'
        ]

    def get_prompt(self):
        return random.choice(self.prompts)

would_you_rather_game = WouldYouRatherGame()
